### PR TITLE
Spelunker Download feature

### PR DESCRIPTION
**Pull request by dphiffer**
This is a new Download feature for the Spelunker inspired by @burritojustice’s [WOF Descender](https://burritojustice.github.io/wof-descender/). It lets you download a bundle of WOF features, encoded as a GeoJSON FeatureCollection or as a CSV summary.

We started out calling it the Descender, but then switched it to "Bundler" to avoid confusion with the other project. And now I'm thinking we should just call it "Downloads" since that's how we labeled the links to it. To make things only slightly more confusing, I'm leaving the JavaScript library called `mapzen.whosonfirst.bundler.js`, which is designed to be reusable elsewhere.

The download feature lives at the path `/download/[WOF id]` and supports the URL argument `?include=[placetype]` to support linking directly to a particular kind of descendant download. Example: https://localhost:8994/download/85977539/?include=borough (download boroughs of NYC)

You can find "download descendants" links:
• From an individual WOF record (under Other, on the right sidebar)
• Above the map on the Descendants results

### CODE REVIEW

**Comment by nvkelso** [comment]
@dphiffer neat! Can you include a few screenshots of what the dev feature looks like, please?

**Comment by dphiffer** [comment]
Screenshots!

screen shot 2016-12-02 at 12 56 26 pm
screen shot 2016-12-02 at 12 56 45 pm
screen shot 2016-12-02 at 12 57 24 pm
screen shot 2016-12-02 at 12 57 52 pm

**Comment by dphiffer** [comment]
Hmm two of those images aren't showing up. Do these work?
screen shot 2016-12-02 at 12 57 24 pm
screen shot 2016-12-02 at 12 57 52 pm

**Comment by nvkelso** [comment]
DUDE, this looks really good :)

**Comment by nvkelso** [comment]
For a followup PR, it would be nice to see a Download link off the landing page for the Spelunker.

**Comment by nvkelso** [comment]
Also big thank you to @stepps00 for work in this PR.

**Comment by thisisaaronland** [comment]
I am going to close this PR without merging it because:

1. There are/were merge conflicts
2. It's been merged in to the `dev-bundler` branch (fixing the merge conflicts)
3. There are some (minor) outstanding issues that need to be fixed before launching this – they are all tracked in [Bundler milestone](https://github.com/whosonfirst/whosonfirst-www-spelunker/milestone/1)

Meanwhile this is enabled and otherwise working on the dev Spelunker. Yay!

**Pull request closed without merging**
